swagger: "2.0"

info:
  description: "Simplest REST API for simulation of transactions."
  version: "1.0.0"
  title: "Digital Hub"
  contact:
    email: "moisestello12@gmail.com"
host: "localhost:5000"
basePath: "/api/"

tags:
- name: "transaction"
  description: "Money movements"
- name: "account"
  description: "Account operations"
schemes:
- "http"
- "https"

paths:
  /transaction:
    post:
      tags:
      - "transaction"
      summary: "transfer money"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: body
        name: body
        schema: 
          type: object
        
      responses:
        '200':
          description: OK
        '400':
          description: Balance insuficient
        '404':
          description: Not Found
  
  /transaction/<account>/<type>:
    get:
      tags:
      - "transaction"
      summary: "Get transactions by type (all, sent or recieved)"
      consumes:
      - "application/json"
      produces:
      - "application/json"
        
      responses:
        '200':
          description: OK
        '404':
          description: No transactions Found
  
  /account/<account>:
    get:
      tags:
      - "account"
      summary: "Get the current balance for a given account"
      consumes:
      - "application/json"
      produces:
      - "application/json"
        
      responses:
        '200':
          description: OK
        '404':
          description: Not Found